### ISSUE TITLE
Release 0.12.2

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#6354]
## Before release

On develop branch:

- [x] Update [CHANGELOG](https://github.com/gogs/gogs/blob/main/CHANGELOG.md) to include entries for the current patch release, `git log v0.12.1...HEAD --pretty=format:'- [ ] %H %s' --reverse`:
	- [x] 98c65f319f4b94a022f3b46bdbcaea21ae934b92 web: correctly serving go-get pages for subdirs (#6318)
	- [x] 672625b55c6989a2fa9e516999255b6eff72aa1f gitutil: infer submodule with baseURL when it is a relative path (#6337)
	- [x] 9044afa40fbe9aaa78b6089573ab9bedb939a39e dep: update github.com/unknwon/cae to v1.0.2 (#6342)
	- [x] ca54cbd05502cd8679a7d7becd878bbb7e21664d action: fix issue reference regexp and error handling (#6352)

## During release

On release branch:

- [x] Update the [hard-coded version](https://github.com/gogs/gogs/blob/main/gogs.go#L21) to the current release, e.g. `0.12.0` -> `0.12.1`.
- [x] Wait for GitHub Actions to complete and no failed jobs.
- [x] Publish a new [GitHub release](https://github.com/gogs/gogs/releases) with entries from [CHANGELOG](https://github.com/gogs/gogs/blob/main/CHANGELOG.md) for the current patch release and all previous releases with same minor version.
- [x] Update all previous GitHub releases with same minor version with the warning:
    ```
    **ℹ️ Heads up! There is a new patch release [0.12.1](https://github.com/gogs/gogs/releases/tag/v0.12.1) available, we recommend directly installing or upgrading to that version.**
    ```
- [x] Wait for a new [Docker Hub tag](https://hub.docker.com/r/gogs/gogs/tags) for the current release to be created automatically.
- [x] Update Docker image tag for the minor release `<MAJOR>.<MINOR>`, e.g. `0.12`.
- [x] Compile and pack binaries (all prefixed with `gogs_<MAJOR>.<MINOR>.<PATCH>_`, e.g. `gogs_0.12.0_`):
	- [x] macOS: `darwin_amd64.zip`
	- [x] Linux: `linux_386.tar.gz`, `linux_386.zip`, `linux_amd64.tar.gz`, `linux_amd64.zip`
	- [x] ARM: `linux_armv7.tar.gz`, `linux_armv7.zip`
	- [x] Windows: `windows_amd64.zip`, `windows_amd64_mws.zip`
- [x] Generate SHA256 checksum for all binaries to the file `checksum_sha256.txt`.
- [x] Upload all binaries to:
	- [x] GitHub release
	- [x] https://dl.gogs.io (also upload `checksum_sha256.txt`)
- [x] Build, push and tag a new Docker image for ARM to [Docker Hub](https://hub.docker.com/r/gogs/gogs-rpi).

## After release

On develop branch:

- [x] Update the repository mirror on [Gitee](https://gitee.com/unknwon/gogs).
- [x] Reply to the release topic for the minor release on [Gogs Discussion](https://discuss.gogs.io/c/announcements/5).
