### ISSUE TITLE
Release 0.12.3

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#6373]
## Before release

On release branch:

- [x] Make sure all commits are cherry-picked from the develop branch by checking the patch milestone.
- [x] Update [CHANGELOG](https://github.com/gogs/gogs/blob/main/CHANGELOG.md) to include entries for the current patch release, e.g. `git log v0.12.1...HEAD --pretty=format:'- [ ] %H %s' --reverse`:
	- [x] 6b6bfe8bb046c6071419b9650bddc0d8c969ed0d cmd/serv: use different log files for ORMs in hook mode (#6361)
	- [x] e6b4c467e83a959f00e9244ef359ea3c8359ca5c markup: render SHA links without branch prefix (#6350)
	- [x] fbe34c8c612ea96409ad24e5be4c05fe96c891f4 lfs: ask client to always send the same value for the HTTP header (#6369)

## During release

On release branch:

- [x] Update the [hard-coded version](https://github.com/gogs/gogs/blob/main/gogs.go#L21) to the current release, e.g. `0.12.0` -> `0.12.1`.
- [x] Wait for GitHub Actions to complete and no failed jobs.
- [x] Publish a new [GitHub release](https://github.com/gogs/gogs/releases) with entries from [CHANGELOG](https://github.com/gogs/gogs/blob/main/CHANGELOG.md) for the current patch release and all previous releases with same minor version.
- [x] Update all previous GitHub releases with same minor version with the warning:
    ```
    **ℹ️ Heads up! There is a new patch release [0.12.1](https://github.com/gogs/gogs/releases/tag/v0.12.1) available, we recommend directly installing or upgrading to that version.**
    ```
- [x] Wait for a new [Docker Hub tag](https://hub.docker.com/r/gogs/gogs/tags) for the current release to be created automatically.
- [x] Update Docker image tag for the minor release `<MAJOR>.<MINOR>`, e.g. `0.12`.
- [x] Compile and pack binaries (all prefixed with `gogs_<MAJOR>.<MINOR>.<PATCH>_`, e.g. `gogs_0.12.0_`):
	- [x] macOS: `darwin_amd64.zip`
	- [x] Linux: `linux_386.tar.gz`, `linux_386.zip`, `linux_amd64.tar.gz`, `linux_amd64.zip`
	- [x] ARM: `linux_armv7.tar.gz`, `linux_armv7.zip`
	- [x] Windows: `windows_amd64.zip`, `windows_amd64_mws.zip`
- [x] Generate SHA256 checksum for all binaries to the file `checksum_sha256.txt`.
- [x] Upload all binaries to:
	- [x] GitHub release
	- [x] https://dl.gogs.io (also upload `checksum_sha256.txt`)
- [x] Build, push and tag a new Docker image for ARM to [Docker Hub](https://hub.docker.com/r/gogs/gogs-rpi).

## After release

On develop branch:

- [x] Post the following message on issues that are included in the patch milestone.
    ```
    The <MAJOR>.<MINOR>.<PATCH> has been released.
    ```
- [x] Update the repository mirror on [Gitee](https://gitee.com/unknwon/gogs).
- [x] Reply to the release topic for the minor release on [Gogs Discussion](https://discuss.gogs.io/c/announcements/5).

**Comment by rakheshster** [comment]
Thanks for this! :) I notice the docker gogs-rpi image hasn't updated while the gogs one has. Is it just a matter of time or did it get missed out?
