### ISSUE TITLE
Release 0.12.4

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#6731]
## Before release

On the release branch:

- [x] Make sure all commits are cherry-picked from the `main` branch by checking the patch milestone.
- [x] Run `git log v0.12.1...HEAD --pretty=format:'- [ ] %H %s' --reverse` (where `v0.12.1` is the last patch release) to get the list of new commits and paste the output below:
	- [x] eb3386c4aac958edc5d592200a892ed3dc3517de context: add X-Frame-Options header (#6411)
	- [x] ec84506da47a187eb6477a78a1fd3d7592082882 repo: disallow urlencoded new lines in git protocol paths (#6420)
	- [x] 5a04c47cf01b5480d3fbfea6df50d5fdd2674299 markup: use default link formation when no format in metas (#6723)
- [x] [Update CHANGELOG on the `main` branch](https://github.com/gogs/gogs/commit/e6c5633f580399c8f4dfc07166a63a01c6c70346) to include entries for the current patch release.

## During release

On the release branch:

- [x] [Update the hard-coded version](https://github.com/gogs/gogs/commit/f0e3cd90f8d7695960eeef2e4e54b2e717302f6c) to the current release, e.g. `0.12.0` -> `0.12.1`.
- [x] Wait for GitHub Actions to complete and no failed jobs.
- [x] Publish new RC releases (e.g. `v0.12.0-rc.1`, `v0.12.0-rc.2`) to ensure Docker wrokflow succeeds. **Make sure the tag is created on the release branch**.
	- [x] Pull down the Docker image and run through application setup to make sure nothing blows up.
- [x] Publish a new [GitHub release](https://github.com/gogs/gogs/releases) with entries from [CHANGELOG](https://github.com/gogs/gogs/blob/main/CHANGELOG.md) for the current patch release and all previous releases with same minor version. **Make sure the tag is created on the release branch**.
	- [x] Only mention patch authors for the current release.
- [x] Update all previous GitHub releases with same minor version with the warning:
	```
	**ℹ️ Heads up! There is a new patch release [0.12.1](https://github.com/gogs/gogs/releases/tag/v0.12.1) available, we recommend directly installing or upgrading to that version.**
	```
- [x] [Wait for a new image tag for the current release](https://github.com/gogs/gogs/actions/workflows/docker.yml?query=event%3Arelease) to be created automatically on both [Docker Hub](https://hub.docker.com/r/gogs/gogs/tags) and [GitHub Container registry](https://github.com/gogs/gogs/pkgs/container/gogs).
- [x] Update Docker image tag for the minor release `<MAJOR>.<MINOR>`, e.g. `0.12` on both [Docker Hub](https://hub.docker.com/r/gogs/gogs/tags) and [GitHub Container registry](https://github.com/gogs/gogs/pkgs/container/gogs).
- [x] Compile and pack binaries (all prefixed with `gogs_<MAJOR>.<MINOR>.<PATCH>_`, e.g. `gogs_0.12.0_`):
	- [x] macOS: `darwin_amd64.zip`, `darwin_arm64.zip`
	- [x] Linux: `linux_386.tar.gz`, `linux_386.zip`, `linux_amd64.tar.gz`, `linux_amd64.zip`
	- [x] ARM: `linux_armv7.tar.gz`, `linux_armv7.zip`, `linux_armv8.tar.gz`, `linux_armv8.zip`
	- [x] Windows: `windows_amd64.zip`, `windows_amd64_mws.zip`
- [x] [Generate SHA256 checksum](https://github.com/gogs/gogs/blob/main/docs/dev/release/sha256.sh) for all binaries to the file `checksum_sha256.txt`.
- [x] Upload all binaries to:
	- [x] GitHub release
	- [x] https://dl.gogs.io (also upload `checksum_sha256.txt`)
- [x] Update content of [Install from binary](https://gogs.io/docs/installation/install_from_binary).

## After release

On the `main` branch:

- [x] Post the following message on issues that are included in the patch milestone:
    ```
    The <MAJOR>.<MINOR>.<PATCH> has been released that includes the patch of the reported issue.
    ```
- [x] Update the repository mirror on [Gitee](https://gitee.com/unknwon/gogs).
- [x] Reply to the release topic for the minor release in [Discussions](https://github.com/gogs/gogs/discussions/categories/announcements).
- [x] Close the patch milestone.
- [x] Send a tweet.

**Comment by unknwon** [comment]
@stypr @matheusmosca I'm so sorry that you got spammed by release notes mentions multiple times today 🤦‍♂️ I kept creating tags on the `main` instead of the release branch today... (sounds like something should also be automated).
